general.import = ["/Users/phutran/.config/alacritty/themes/themes/ayu_dark.toml"]
general.working_directory = "/Users/phudtran/personal/"

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 20

[font.normal]
family = "FiraCode Nerd Font Mono"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "Buttonless"
opacity = 0.9 
startup_mode = "Windowed"
blur = true 

[window.dimensions]
columns = 125
lines = 38

[window.padding]
x = 10
y = 10
